### ISSUE TITLE
Initial commit & readme

### ISSUE THREAD

**Issue by alce65** [Allorentee/202210-W3CH5-alvaro-llorente#3]
Hola Alvaro.
El commit inicial no debe incluir un readme sin contenido.
Tiene que incluir UN CONTENIDO VÁLIDO: al menos las instrucciones para hacer el challenge.
Esto YA lo deberías tener desde el principio.

**Comment by Allorentee** [comment]
Buenas Alejandro, subo la corrección  de readme, gracias por la observacion!

**Comment by alce65** [comment]
De nada. Cierro el issue
