### ISSUE TITLE
Branch for the work in progress 

### ISSUE THREAD

**Issue by alce65** [Allorentee/202210-W3CH5-alvaro-llorente#7]
Hola Alvaro.
Veo que solo tienes la rama main en Github y supongo que ahora estarás trabajando en algo,
Recuerda que la rama con la feature en la que estemos trabajando se sube a remoto en cuanto tiene algún contenido. No hay que esperar a que este lista para la PR. De esta forma estamos salvaguardando nuestro trabajo en Github, por si acaso pasara algo en local.

**Comment by Allorentee** [comment]
Perfecto, lo tengo en cuenta.
Muchas gracias.

**Comment by alce65** [comment]
Muy bien. Entonces cierro la PR
